/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tcm;
/**
 *
 * @author lenovo
 */
public class Splash extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public Splash(){
    initComponents();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        progressbar = new javax.swing.JProgressBar();
        loadingpercentage = new javax.swing.JLabel();
        red = new javax.swing.JLabel();
        tcm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TCM");
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        progressbar.setForeground(java.awt.Color.lightGray);
        jPanel1.add(progressbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 670, 10));

        loadingpercentage.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        loadingpercentage.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.add(loadingpercentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 520, 50, 30));

        red.setFont(new java.awt.Font("Calibri", 1, 250)); // NOI18N
        red.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        red.setText(".");
        red.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(red, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 130));
        red.getAccessibleContext().setAccessibleName("red");

        tcm.setFont(new java.awt.Font("Segoe UI Black", 0, 100)); // NOI18N
        tcm.setForeground(new java.awt.Color(255, 102, 0));
        tcm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tcm.setText("TCM");
        jPanel1.add(tcm, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 270, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcm/icons/65c1157d-3fc8-423b-98b4-795d75ee3819.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(667, 563));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel loadingpercentage;
    public javax.swing.JProgressBar progressbar;
    public javax.swing.JLabel red;
    public javax.swing.JLabel tcm;
    // End of variables declaration//GEN-END:variables
}
